package video

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
)

type Comment struct {
	Vpos      int    `json:"vpos"`
	Timestamp int    `json:"timestamp"`
	Author    string `json:"author"`
	Message   string `json:"message"`
}

type ASSGenerator struct {
	Width           int
	Height          int
	FontSize        int
	FontName        string
	DurationMarquee float64
	DurationStill   float64
	BottomReserved  int
}

func NewASSGenerator() *ASSGenerator {
	return &ASSGenerator{
		Width:           683,
		Height:          384,
		FontSize:        25,
		FontName:        "MS PGothic",
		DurationMarquee: 5.0,
		DurationStill:   5.0,
		BottomReserved:  0,
	}
}

func (g *ASSGenerator) GenerateFromJSON(inputPath, outputPath string) error {
	f, err := os.Open(inputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	var comments []Comment
	if err := json.NewDecoder(f).Decode(&comments); err != nil {
		return err
	}

	// Adjust vpos if missing (for legacy JSON files)
	for i := range comments {
		if comments[i].Vpos == 0 && comments[i].Timestamp > 0 {
			comments[i].Vpos = comments[i].Timestamp * 100
		}
	}

	return g.Generate(comments, outputPath)
}

func (g *ASSGenerator) Generate(comments []Comment, outputPath string) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	sort.Slice(comments, func(i, j int) bool {
		return comments[i].Vpos < comments[j].Vpos
	})

	styleID := "Danmaku"
	g.writeHeader(f, styleID)

	rowCount := (g.Height - g.BottomReserved) / g.FontSize
	
	// 各行の「最後に投入されたコメント」の情報を保持する
	type lastCommentInfo struct {
		startTime float64
		msgWidth  int
		speed     float64
	}
	lastComments := make([]lastCommentInfo, rowCount)
	for i := range lastComments {
		lastComments[i].startTime = -100.0 // 十分に前の時間
	}
	
	for _, c := range comments {
		timeline := float64(c.Vpos) / 100.0
		if timeline < 0 {
			timeline = 0
		}

		// 文字列の幅を推定 (すべて全角として計算)
		msgWidth := len([]rune(c.Message)) * g.FontSize
		// このコメントの移動速度 v = (Width + msgWidth) / Duration
		currentSpeed := float64(g.Width+msgWidth) / g.DurationMarquee

		foundRow := -1
		// 衝突しない行を探す
		for i := 0; i < rowCount; i++ {
			lc := lastComments[i]
			
			// 1. 入口での衝突判定: 
			// 前のコメントの末尾が画面右端に入り切る時間
			timeToEnter := lc.startTime + float64(lc.msgWidth)/lc.speed
			if timeline < timeToEnter {
				continue
			}

			// 2. 出口での衝突判定 (追い越し判定):
			// 前のコメントが画面左端に消える時間 (lc.startTime + Duration) において、
			// 自分の頭がまだ画面内に残っている必要がある。
			// 自分の位置 x = Width - currentSpeed * (t - timeline)
			// t = lc.startTime + Duration のとき x >= 0 であればよい。
			// Width - currentSpeed * (lc.startTime + g.DurationMarquee - timeline) >= 0
			// => timeline >= lc.startTime + g.DurationMarquee - Width/currentSpeed
			timeToAvoidChase := lc.startTime + g.DurationMarquee - float64(g.Width)/currentSpeed
			if timeline < timeToAvoidChase {
				continue
			}

			foundRow = i
			break
		}

		if foundRow == -1 {
			// 空きがない場合は、一番「マシ」な行を選ぶ（今回は簡易的に0行目にするか、最小待ち時間の行を探す）
			// 本来は待ち時間を加算して timeline をずらすのが danmaku2ass 流ですが、
			// 縦に広がるのを防ぐため、ここでは最小の待ち時間で済む行を探します。
			bestRow := 0
			minWait := 100.0
			for i := 0; i < rowCount; i++ {
				lc := lastComments[i]
				wait1 := (lc.startTime + float64(lc.msgWidth)/lc.speed) - timeline
				wait2 := (lc.startTime + g.DurationMarquee - float64(g.Width)/currentSpeed) - timeline
				wait := math.Max(wait1, wait2)
				if wait < minWait {
					minWait = wait
					bestRow = i
				}
			}
			foundRow = bestRow
			if minWait > 0 {
				timeline += minWait
			}
		}

		y := foundRow * g.FontSize

		// 情報を更新
		lastComments[foundRow] = lastCommentInfo{
			startTime: timeline,
			msgWidth:  msgWidth,
			speed:     currentSpeed,
		}

		startTimeStr := g.formatTimestamp(timeline)
		endTimeStr := g.formatTimestamp(timeline + g.DurationMarquee)
		text := g.escapeASS(c.Message)

		line := fmt.Sprintf("Dialogue: 2,%s,%s,%s,,0000,0000,0000,,{\\move(%d,%d,%d,%d)}%s\n",
			startTimeStr, endTimeStr, styleID, g.Width, y, -msgWidth, y, text)
		f.WriteString(line)
	}

	return nil
}

func (g *ASSGenerator) writeHeader(f *os.File, styleID string) {
	header := fmt.Sprintf(`[Script Info]
; Script generated by NicoDanmaku2ASS
ScriptType: v4.00+
PlayResX: %d
PlayResY: %d
Aspect Ratio: %d:%d
Collisions: Normal
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: %s, %s, %d, &H11FFFFFF, &H11FFFFFF, &H77000000, &H77000000, 1, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 2, 0, 7, 0, 0, 0, 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`, g.Width, g.Height, g.Width, g.Height, styleID, g.FontName, g.FontSize)
	f.WriteString(header)
}

func (g *ASSGenerator) formatTimestamp(seconds float64) string {
	if seconds < 0 {
		seconds = 0
	}
	totalCs := int(math.Round(seconds * 100))
	h := totalCs / 360000
	m := (totalCs % 360000) / 6000
	s := (totalCs % 6000) / 100
	cs := totalCs % 100
	return fmt.Sprintf("%d:%02d:%02d.%02d", h, m, s, cs)
}

func (g *ASSGenerator) escapeASS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "{", "\\{")
	s = strings.ReplaceAll(s, "}", "\\}")
	s = strings.ReplaceAll(s, "\n", "\\N")
	return s
}
